### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### What does this implement/fix? Explain your changes.
- `README.md` updated
- `dependabot.yml` added
- Minor edits in `RELEASE.md`

### CODE REVIEW

**Comment by sadrasabouri** [comment]
@sepandhaghighi Can you also fix Codacy failing status for `dev` branch on MacOS and Linux?
[Linux Failing Codacy Badge](https://github.com/openscilab/nava/workflows/Linux/badge.svg?branch=dev)

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Can you also fix Codacy failing status for `dev` branch on MacOS and Linux? [Linux Failing Codacy Badge](https://github.com/openscilab/nava/workflows/Linux/badge.svg?branch=dev)

Fixed in https://github.com/openscilab/nava/pull/38/commits/f815f732f757ee1b57bd2bde9196b047002b5c88

**Comment by sadrasabouri** [comment]
I would test it on MacOS tomorrow and review this process.

**Review by sadrasabouri — APPROVED** [review]
I checked it on MacOS and yes it can also play `mp3`.

**Pull request merged**
