### PR TITLE
Async feature implementation using threading library

### PR DESCRIPTION
**Pull request by NimaSamadi007**
Due to the previous inconsistencies of async feature implementation, the `threading` library is used to implement the async-like sound-playing feature. Tests are provided in the `test` directory. Github build fails due to some issues with the `function_test.py` script which I'm not sure why. 
It seems that when the parent thread of the subprocess is dead, its child process doesn't die automatically. In other words, in async mode, if the user program ends before the sound playing is finished, the user can hear the voice although the program is terminated. Therefore, it seems that we need some sort of cleanup procedure to kill/terminate these child threads so they don't end up being zombie processes.  The best way to do this is to use class destructors but as of now, the code is more function-oriented rather than object-oriented. For now, I used Python's `atexit` library to run the cleanup procedure. Any other comments are welcome!

### CODE REVIEW

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@NimaSamadi007 Well done 💯 
This approach looks good to me!

1. I think it would be better to return `proc` in the `__play_sync_linux` function instead of declaring a new function like ` __play_non_blocking_linux`. This work will prevent future duplications.

2. It seems there is a minor issue in import/call of the `__cleanup_processes` function in `__init__.py`

3. Continue your work for other platforms

Good luck 🔥

**Comment by NimaSamadi007** [comment]
Thanks 🙏, that's great.

+ Yeah sure. I will call `__play_sync_linux` in the thread target function. However, it seems that there's no straightforward way to access the return value of the thread. There are two approaches:
    1. Use a global variable or an input variable that acts like the return value (similar to what's done in C)
    2.  Modify `run()` method in class definition
I will use the first approach and always save the process handler in a list.
+ I will test it again. Thanks for mentioning.
+ Yeah sure. I will also develop the code for Windows, but I'm not sure how I'm supposed to test the code for MacOS.

**Comment by NimaSamadi007** [comment]
Hello all. I implemented the Windows async feature and applied the requested codebase changes. Please help to check it. I don't have access to a MacOS-based device. So, I couldn't implement the async feature for MacOS. Should I install it in a virtualized environment and work on it or do you have any other suggestions? I haven't worked with MacOS before so I don't know if it's even possible to do this.

**Comment by sadrasabouri** [comment]
> Hello all. I implemented the Windows async feature and applied the requested codebase changes. Please help to check it. I don't have access to a MacOS-based device. So, I couldn't implement the async feature for MacOS. Should I install it in a virtualized environment and work on it or do you have any other suggestions? I haven't worked with MacOS before so I don't know if it's even possible to do this.

Thanks Nima. You just needed to implement macOS by replacing `aplay` by `afplay`.  I will test it in my friend's laptop.

**Comment by NimaSamadi007** [comment]
I implemented the macOS async feature similar to Linux implementation. By the way, in Windows, you can specify a flag to play the sound in async mode and you don't need to worry about the underlying process getting killed or not and everything is handled in `winsound`. However, this causes some sort of inconsistent API across different operating systems. In other words, in Windows, high-level users won't get any thread handler while that's not the case in Linux and macOS. I'm not sure if it's okay or not.

**Review by sadrasabouri — CHANGES_REQUESTED** [review]
Thanks Nima. It looks good to me.
Just remove `test/__init__.py` and `test/main.py`. We will add tests for it after this PR.

**Review by sadrasabouri — APPROVED** [review]

**Review by sepandhaghighi — APPROVED** [review]
🚀

**Pull request merged**
