### PR TITLE
`NavaThread` exception

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### What does this implement/fix? Explain your changes.
- `NavaThread` exception bug fixed
#### Local tests on OSs

- [x] macOS
    - [x] Sonoma
- [x] Windows
    - [x] Windows 11
- [ ] Linux
    - [ ] Ubuntu 20.04

### CODE REVIEW

**Review by sadrasabouri — APPROVED** [review]
LGTM.
Just a point I wanted to mention here for future reference. Since we are using `WINSOUND` API, but call `alsa` directly from the system, they still have difference.
For example in MacOS, for async mode, when running Winsound, it gave the error and process is done, but when calling Alsa, it stuck and needed a `Ctrl + C` to exit.

You can merge it, I just don't merge it so that you see my message here.

**Comment by sepandhaghighi** [comment]
> LGTM. Just a point I wanted to mention here for future reference. Since we are using `WINSOUND` API, but call `alsa` directly from the system, they still have difference. For example in MacOS, for async mode, when running Winsound, it gave the error and process is done, but when calling Alsa, it stuck and needed a `Ctrl + C` to exit.
> 
> You can merge it, I just don't merge it so that you see my message here.

What's the meaning of stuck? It's really weird! This process run on another thread. Can you provide a reproducible example?

**Comment by sadrasabouri** [comment]
> > LGTM. Just a point I wanted to mention here for future reference. Since we are using `WINSOUND` API, but call `alsa` directly from the system, they still have difference. For example in MacOS, for async mode, when running Winsound, it gave the error and process is done, but when calling Alsa, it stuck and needed a `Ctrl + C` to exit.
> > You can merge it, I just don't merge it so that you see my message here.
> 
> What's the meaning of stuck? It's really weird! This process run on another thread. Can you provide a reproducible example?

Yes, checkout this on Ubuntu (for example) and see the differnece:
```pycon
play("path/to/file.wav", engine=Engine.WINSOUND)
```
and 
```pycon
play("path/to/file.wav", engine=Engine.AFPLAY)
```

**Review by sadrasabouri — APPROVED** [review]

**Comment by sadrasabouri** [comment]
We decided to fix the raised issue in a separate PR.

**Pull request merged**
